In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder

from sklearn.compose import ColumnTransformer

from sklearn.cluster import KMeans
from sklearn.cluster import AgglomerativeClustering

from sklearn.metrics import silhouette_score
from sklearn.metrics import davies_bouldin_score
from sklearn.metrics import calinski_harabasz_score

from sklearn.decomposition import PCA
from sklearn.manifold import TSNE

from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

from scipy.cluster.hierarchy import dendrogram, linkage

In [5]:
df = pd.read_csv("store.csv")
print("Dataset loaded Succesfully")
print("Shape of dataset :",df.shape)
df.head()

Dataset loaded Succesfully
Shape of dataset : (10000, 5)

     reps product  qty  revenue region
0  Chitra  Galaxy    2   155.10   West
1   Vijay     Jet    2    39.30  North
2    Mala  Beacon    3    74.25   West
3   Suman   Alpen    3   100.98  North
4  Rachna   Orbit    2    44.98  North

In [6]:
print("Number of rows :",df.shape[0])
print("Number of columns :",df.shape[1])
print("\nColumn names\n")
print(df.columns)
print("\nData Types\n")
print(df.dtypes)

Number of rows : 10000
Number of columns : 5

Column names

Index(['reps', 'product', 'qty', 'revenue', 'region'], dtype='str')

Data Types

reps           str
product        str
qty          int64
revenue    float64
region         str
dtype: object

In [7]:
print("Missing Values in each columns: ")
print(df.isnull().sum())

Missing Values in each columns:
reps       0
product    0
qty        0
revenue    0
region     0
dtype: int64

In [8]:
print("Stastical Summary")
df.describe()

Stastical Summary

                qty       revenue
count  10000.000000  10000.000000
mean       3.387400     90.570221
std        4.318308    127.803928
min        1.000000     18.430000
25%        2.000000     39.300000
50%        2.000000     58.425000
75%        3.000000     75.000000
max       25.000000   1998.750000

In [9]:
print("Unique values in categorical columns: ")
print("\nReps:")
print(df["reps"].unique())
print("\nProduct:")
print(df["product"].unique())
print("\nRegion:")
print(df["region"].unique())

Unique values in categorical columns:

Reps:
<ArrowStringArray>
[ 'Chitra',   'Vijay',    'Mala',   'Suman',  'Rachna',    'Aash',   'Chand',
   'Suraj',    'Bala',    'Seet',    'Ravi',  'Anusha',  'Ananya',   'Jaggi',
    'Reva',   'Meena',     'Sai',   'Rahul',     'Ram',  'Prarth',   'Pooja',
   'Rishi',   'Ranga',    'Sesh', 'Shaanth', 'Bharath',   'Susan',   'Ratna',
  'Easwar',  'Prasad',   'Madhu',  'Suresh',  'Anahit',  'Sumedh',   'Manju',
 'Nandini', 'Santosh',  'Satyen',  'Vaghya',   'Palak',  'Aparna', 'Jagdish',
    'Vish',   'Kumar',    'John',    'Bhat', 'Hussain',    'Alka',  'Rohini',
  'Keshab',   'Nidhi',   'Satya',  'Venkat',  'Veeyes',   'Rajat', 'Chandra',
   'Kamat',    'Raji',   'Swami',     'Jay',  'Mukund',   'Priya',  'Kishen',
   'Vidya',   'Akila',   'Durga',     'Mak',   'Mehta',   'Javed',   'Sruti',
  'Mukesh', 'Kishore']
Length: 72, dtype: str

Product:
<ArrowStringArray>
[ 'Galaxy',     'Jet',  'Beacon',   'Alpen',   'Orbit', 'Trident',    'Mars',
   'Milka',  'Almond',  'Prince',    'Star',   'Halls']
Length: 12, dtype: str

Region:
<ArrowStringArray>
['West', 'North', 'East', 'South']
Length: 4, dtype: str